# Ronnie Quotes
RONNIE_QUOTES = [
    "YEAH BUDDY!",
    "LIGHTWEIGHT BABY!",
    "AIN'T NUTHIN' BUT A PEANUT!",
    "EVERYBODY WANTS TO BE A BODYBUILDER, BUT NOBODY WANTS TO LIFT NO HEAVY-ASS WEIGHTS!",
    "I'LL DO IT!",
    "TIME TO BLEED!",
    "CALL THE COPS! CALL THE AMBULANCE!",
    "WOOOOOO!"
]

# Action Quotes
RONNIE_CLEAR_QUOTES = [
    "SWEEPING THE FLOOR LIKE IT'S 800 LBS SQUATS!",
    "CLEANED UP THAT TRASH! AIN'T NUTHIN' BUT A PEANUT!",
    "WIPED OUT THOSE MESSAGES! LIGHTWEIGHT!"
]

RONNIE_KICK_QUOTES = [
    "BOOTED OUT! NOT ENOUGH INTENSITY!",
    "GET OUTTA HERE! GO LIFT SOME HEAVY WEIGHTS FIRST!",
    "KICKED TO THE CURB! YEAH BUDDY!"
]

RONNIE_BAN_QUOTES = [
    "PERMANENTLY BANNED! NO PAIN NO GAIN!",
    "HAMMER BROUGHT DOWN! WE DON'T TOLERATE SLACKERS!",
    "BANHAMMERED OUT OF THE GYM!"
]

RONNIE_MUTE_QUOTES = [
    "PUT ON TIMEOUT! GO TAKE A REST DAY!",
    "MUTED! TIME TO RECOVER AND BE QUIET!",
    "NO TALKING IN THE SQUAT RACK! TIMEOUT APPLIED!"
]